#Eureka server服务端口
server:
  port: 8763
spring:
  application:
    name: lagou--cloud-eureka-server # 应用名称，会在Eureka中作为服务的id标识（serverId)
eureka:
  # 关闭自我保护模式（缺省为打开）  建议生产环境打开自我保护模式
  server:
    enable-self-preservation: false
  instance:
    hostname: LagouCloudEurekaServerC # 当前eureka实例的主机名
  client:
    service-url: #客户端与EurekaServer交互的地址，如果是集群，也需要写其他的server地址,指向其他eureka server    #  http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka,http://LagouCloudEurekaServerB:8762/eureka
    register-with-eureka: true  # 集群模式下可以改为 true    如果就自己一个服务 就不需要注册
    fetch-registry: true      #⾃⼰就是服务不需要从Eureka Server获取服务信息,默认为true，如果自己一个服务                                                                                 置为false
  dashboard:
    enabled: true
